### ISSUE TITLE
An attempt to sanitize memory with CLANG seems to betray a bug.

### ISSUE THREAD

**Issue by FlatAssembler** [FlatAssembler/AECforWebAssembly#4]
I just noticed that the CLANG sanitizer claims my compiler does not behave properly when it comes to memory management. Here is a session that exemplifies that:
```
[teo.samarzija@teos-acer-laptop AECforWebAssembly]$ clang++ -fsanitize=memory -o aec AECforWebAssembly.cpp -g
[teo.samarzija@teos-acer-laptop AECforWebAssembly]$ lldb aec
(lldb) target create "aec"
Current executable set to '/home/teo.samarzija/Documents/AECforWebAssembly/aec' (x86_64).
(lldb) run nQueensPuzzle/nQueensPuzzle.aec
Process 10558 launched: '/home/teo.samarzija/Documents/AECforWebAssembly/aec' (x86_64)
==10558==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x65bed2 in std::ctype<char> const const& std::use_facet<std::ctype<char> const>(std::locale const&) /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/locale_classes.tcc:135:55
    #1 0x65898d in std::__detail::_Scanner<char const*>::_Scanner(char const*, char const*, unsigned int, std::locale) /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/regex_compiler.h:111:18
    #2 0x657916 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_Compiler(char const* const&, char const* const&, std::regex_traits<char>&, unsigned int) /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/regex_compiler.h:721:28
    #3 0x65708b in std::shared_ptr<std::__detail::_Automaton> std::__detail::__compile<char const*, std::regex_traits<char> >(char const* const&, char const* const&, std::regex_traits<char>&, unsigned int) /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/regex_compiler.h:1104:37
    #4 0x5a4286 in std::basic_regex<char, std::regex_traits<char> >::basic_regex(char const*, unsigned int) /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/regex.h:387:22
    #5 0x57008b in main /home/teo.samarzija/Documents/AECforWebAssembly/AECforWebAssembly.cpp:35:32
    #6 0x7ffff6ae02da in __libc_start_main /home/teo.samarzija/glibc/csu/../csu/libc-start.c:308:16
    #7 0x41faf9 in _start /home/teo.samarzija/glibc/csu/../sysdeps/x86_64/start.S:120

SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../include/c++/4.8.5/bits/locale_classes.tcc:135:55 in std::ctype<char> const const& std::use_facet<std::ctype<char> const>(std::locale const&)
Exiting
Process 10558 exited with status = 77 (0x0000004d) 
(lldb) 
```
So, apparently, [my test of whether the C++ compiler supports regular expressions](https://github.com/FlatAssembler/AECforWebAssembly/blob/a67e779fca049f05da58c3186968f40f04145ee8/AECforWebAssembly.cpp#L35) somehow leads to using an uninitialized variable. I am not sure how that is possible.

**Comment by FlatAssembler** [comment]
Here is what Valgrind outputs:
```
❯ valgrind ./aec ../nQueensPuzzle/nQueensPuzzle.aec
==346659== Memcheck, a memory error detector
==346659== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==346659== Using Valgrind-3.16.1 and LibVEX; rerun with -h for copyright info
==346659== Command: ./aec ../nQueensPuzzle/nQueensPuzzle.aec
==346659== 
Running the tests...
All the tests passed in 14721 milliseconds.
Reading the file...
All characters read in 12 milliseconds.
Tokenizing the program...
Finished tokenizing the program in 1433493 milliseconds.
Parsing the program...
Finished parsing the program in 35783 milliseconds.
Compiling the program...
Compilation finished in 63259 milliseconds!
Saving the assembly in file "../nQueensPuzzle/nQueensPuzzle.wat"...
Assembly successfully saved, quitting now.
==346659== 
==346659== HEAP SUMMARY:
==346659==     in use at exit: 0 bytes in 0 blocks
==346659==   total heap usage: 88,110,509 allocs, 88,110,509 frees, 2,078,431,847 bytes allocated
==346659== 
==346659== All heap blocks were freed -- no leaks are possible
==346659== 
==346659== For lists of detected and suppressed errors, rerun with: -s
==346659== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
valgrind ./aec ../nQueensPuzzle/nQueensPuzzle.aec  1546,01s user 0,76s system 99% cpu 25:48,82 total```
This seems to suggest this was a false positive.
